language: generic
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: $AWS_SECRET_KEY
  region: "eu-central-1"
  app: "septa"
  env: "septa-website"
  bucket_name: "elasticbeanstalk-eu-central-1-243829800264"
  bucket_path: "/travis-builds/"
  on:
    branch: master