version: "3.9"

services:
  web:
    build: ./
    command: /bin/sh -c "python manage.py migrate --no-input && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    working_dir: /code
  db:
    image: postgres:13.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    healthcheck:
      test: ./postgres_heathcheck.sh
      interval: 1s

volumes:
  postgres_data: