version: "3.9"

services:
  web:
    build: ./web
    volumes:
      - static_volume:/home/app/web/static/
      - media_volume:/home/app/web/media/
    expose:
      - 8000
    depends_on:
      - db
    environment:
      - DOPPLER_TOKEN
  db:
    image: postgres:13.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
  nginx:
    build: ./nginx
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - web
    volumes:
      - static_volume:/home/app/web/static/
      - media_volume:/home/app/web/media/

volumes:
  postgres_data:
  static_volume:
  media_volume: