# Generated by Django 3.1.1 on 2020-11-17 17:41

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
