#cloud-config
ssh_pwauth: no
users:
  - name: septa
    groups: sudo
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
    ssh_authorized_keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKGApXn+0UKtQZBMqa3jysbdUez9GPwpo7QA57IfGk4r shevela@tochka.com"
