# Generated by Django 3.1.1 on 2021-06-14 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210530_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_leader',
        ),
        migrations.AlterField(
            model_name='team',
            name='leader',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leading_team', to=settings.AUTH_USER_MODEL),
        ),
    ]
