# Generated by Django 3.1.1 on 2021-07-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210614_1316'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(fields=('team', 'user'), name='unique invitation'),
        ),
    ]
