# Generated by Django 3.1.1 on 2021-02-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210205_2325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=9),
        ),
    ]
