# Generated by Django 3.1.1 on 2021-07-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_auto_20210717_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
