# Generated by Django 3.1.1 on 2021-08-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_team_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.IntegerField(db_index=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
