name: Build docker image
on:
  workflow_call:
    outputs:
      image_tag:
        description: "Built image tag"
        value: ${{jobs.build.outputs.image_tag}}
  workflow_dispatch:
jobs:
  build:
    environment: production
    runs-on: ubuntu-latest
    env:
      REPO: cr.yandex/crp9d7sqskl7c428opg7/portal
    steps:
      -
        name: Check out code
        uses: actions/checkout@v2
      -
        name: Login Yandex Cloud Container Registry
        uses: docker/login-action@v1
        with:
          registry: cr.yandex
          username: json_key
          password: ${{ secrets.YC_SA_AUTHORIZED_KEY_JSON }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: ./web
          push: true
          tags: ${{ env.REPO }}:${{ github.sha }}, ${{ env.REPO }}:latest