name: Database
on:
  workflow_call:
  workflow_dispatch:
jobs:
  update-infrastruture:
    runs-on: ubuntu-latest
    environment: production
    steps:
      -
        name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      -
        name: Check out code
        uses: actions/checkout@v2
      -
        name: Upgrade infrastructure
        working-directory: terraform/database
        env:
          YC_SERVICE_ACCOUNT_KEY_FILE: ${{ secrets.YC_SA_AUTHORIZED_KEY_JSON }}
          YC_SA_STATIC_KEY_JSON: ${{ secrets.YC_SA_STATIC_KEY_JSON }}
          YC_CLOUD_ID: ${{ secrets.YC_CLOUD_ID }}
          YC_FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}
          YC_ZONE: ${{ secrets.YC_ZONE }}
          AWS_REGION: ${{ secrets.YC_ZONE }}
        run: |
          # AWS S3 backend provided by terraform to store state
          export AWS_ACCESS_KEY_ID=$(echo $YC_SA_STATIC_KEY_JSON | jq -r ".access_key.key_id")
          export AWS_SECRET_ACCESS_KEY=$(echo $YC_SA_STATIC_KEY_JSON | jq -r ".secret")
          
          # Yandex.Cloud S3 to load remote state and to create buckets
          export YC_STORAGE_ACCESS_KEY="$AWS_ACCESS_KEY_ID"
          export YC_STORAGE_SECRET_KEY="$AWS_SECRET_ACCESS_KEY"
          
          terraform init -upgrade
          terraform plan -input=false
          terraform apply -auto-approve -input=false